application/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from application import db
from datetime import datetime
from application import login_manager
import bleach # 清除多余的html标签
from markdown import markdown
from flask import current_app


# 数据库类似于一个仓库
class User(UserMixin,db.Model):

    __tablename__ = 'user'

    id=db.Column(db.Integer,primary_key=True,autoincrement=True)

    username=db.Column(db.String(30),nullable=False)# 不为空

    _password_hash=db.Column(db.String(256))

    phonenum=db.Column(db.Integer,nullable=False)

    email_ad=db.Column(db.String(30))

    user_img=db.Column(db.String(255),default='../static/imgs/users.jpg')
    
    articles = db.relationship("Article",backref="user")# backref="user"  提供反向引用的接口    可以通过文章反向找到作者  article.user
                                                       # lazy 决定了什么时候从数据库中加载数据
    role_id = db.Column(db.Integer, db.ForeignKey("role.id"))


    @property
    def password(self):#    用户调用密码,能看(哈希值)不能改   使得password == self._password_hash
        return self._password_hash

    @password.setter#   存储密码于db  and  修改密码
    def set_password(self, in_word):
        self._password_hash = generate_password_hash(in_word)

    def check_password(self, in_word):  # 验证密码   返回True/False
        return check_password_hash(self._password_hash, in_word)

    @property
    def is_authenticated(self):
        return True

    def __init__(self, **kwargs):   # 根据邮箱设置角色权限
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(permission=0xff).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

@login_manager.user_loader#       读取用户
def user_loader(user_id):
    user = User.query.get(int(user_id))
    return user


class Article(db.Model):
    __tablename__ = 'article'

    id = db.Column(db.Integer, primary_key=True)

    title = db.Column(db.String(128))

    body = db.Column(db.Text)

    body_html = db.Column(db.Text)# 存放被转换成html格式的文本

    # 外键 同步到数据库的外键关系   存在于表中，且是与User类互相映射的桥梁
    author_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    create_time = db.Column(db.String(50), default=datetime.now().strftime('%Y-%m-%d %H:%M'))

    categories = db.Column(db.String(20))

    num_like = db.Column(db.Integer)
    num_comment = db.Column(db.Integer)
    num_visited = db.Column(db.Integer)

    @staticmethod
    # 当某个方法不需要用到对象中的任何资源, 将这个方法改为一个静态方法, 加一个 @ staticmethod
    # 加上之后, 这个方法就和普通的函数没有什么区别了, 只不过写在了一个类中, 可以使用这个类的对象调用,
    # 也可以使用类直接调用,
    def on_changed_body(target, value, oldvalue, initiator):

        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p', 'img', 'video', 'div', 'iframe', 'p', 'br', 'span', 'hr', 'src', 'class']
        allowed_attrs = {'*': ['class'],
                         'a': ['href', 'rel'],
                         'img': ['src', 'alt']}
        target.body_html = bleach.linkify(# 作用是将html文本中的url转换成<a>
                            bleach.clean(
                            markdown(value, output_format='html'),
                            tags=allowed_tags,
                            strip=True,
                            attributes=allowed_attrs
                                )
                            )
db.event.listen(Article.body, 'set', Article.on_changed_body)


class Permissions(db.Model):
    __tablename__ = 'permission'

    id = db.Column(db.Integer, primary_key=True)

    FOLLOW = 0X01

    FOLLOWED = 0X02

    WRITE_ARTICLE = 0X04

    COMMENT = 0X08

    ADMIN = 0X80


class Role(db.Model):
    __tablename__ = "role"

    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(128), unique=True)

    default = db.Column(db.Boolean, default=False, index=True)

    permissions = db.Column(db.Integer)

    users = db.relationship('User', backref='role')# backref参数则对关系提供反向引用的声明。                                                        # 子查询方式(subquery)

    @staticmethod
    def init_role():
        roles = {          #  身份权限映射
            'user': [Permissions.WRITE_ARTICLE,Permissions.COMMENT,Permissions.FOLLOW,Permissions.FOLLOWED],
            'admin': (0xff,False)
        }
        try:
            for r in roles:
                role = Role.query.filter_by(name=r).first()#　角色名为用户的第一个
                if role is None:    # 如果查询结果为空
                    role = Role(name=r)         # 加入类型
                role.permissions=role[r][0]    #   　重置其permissions === 0
                role.default = role[r][1]
                db.session.add(role)
            db.session.commit()
        except: # 若发生异常，撤销刚刚的操作
            db.session.rollback()
        db.session.close()


    def has_permission(self, permission):
        return self.permissions & permission == permission

application/admin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileAllowed
from wtforms import StringField, PasswordField,SubmitField,FileField
from wtforms.validators import DataRequired

class ChangePsd(FlaskForm):
    pre_username = StringField(validators=[DataRequired()])
    pre_phonenum = StringField(validators=[DataRequired()])
    pre_email_ad = StringField(validators=[DataRequired()])
    proofcode = StringField(validators=[DataRequired()])
    new_password = PasswordField(validators=[DataRequired()])
    submit = SubmitField('点击找回密码')

class Upload_img(FlaskForm):
    user_img = FileField(validators=[FileRequired(), FileAllowed(['jpg'])])
    submit = SubmitField('上传')

application/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired

class CreatePost(FlaskForm):
    title = StringField('博客标题',validators=[DataRequired()])
    body = TextAreaField('博客内容',validators=[DataRequired()])
    categories = SelectField('分类',choices=[("notes","学习笔记"),("affair","生活记事"),("water","注水~"),("other","其他")])
    submit = SubmitField("发布")

    # def __init__(self):
    #     super(CreatePost, self).__init__()
    #     self.categories.choices = [(c.id, c.title) for c in Category.query.order_by('id')]

application/__init__.py
# app的初始化
# -*- coding: utf-8 -*-
from flask import Flask
from config import config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flaskext.markdown import Markdown
from flask_admin import Admin


my_email=Mail()
db = SQLAlchemy()
login_manager=LoginManager()


admin_it=Admin()
def create_app(config_name):
    '''程序的工厂函数'''
    app = Flask(__name__)
    app.config.from_object(config[config_name])


    # 初始化扩展

    db.init_app(app)

    login_manager.init_app(app)
    login_manager.login_view="auth.login"# 未登录  跳转到login界面
    login_manager.login_message = ("请先登录再访问呀~")

    my_email.init_app(app)
    Markdown(app)
    admin_it.init_app(app)
    # 注册蓝本
    from application.auth import auth_blue
    app.register_blueprint(auth_blue)

    from application.main import main_blue
    app.register_blueprint(main_blue)

    from application.admin import admin_blue_1
    app.register_blueprint(admin_blue_1)

    from application.blog import blog_blue
    app.register_blueprint(blog_blue)

    return app

application/admin/__init__.py
from flask import Blueprint

admin_blue_1 = Blueprint('admin_1',__name__)

from . import views,forms,modelViews

application/admin/views.py
from . import admin_blue_1
from .forms import ChangePsd,Upload_img
from flask import render_template, redirect, flash, request, jsonify ,session
from flask_login import login_required,current_user
from application import db
from application.models import User
import base64,os

# 个人主页
@admin_blue_1.route('/userspace/<id>')
@login_required
def user_space(id):
    return render_template("/admin/myspace.html")



# 要判断邮箱是不是对应用户注册时用的邮箱...不然盗号太容易了。。。**************注意************
# 找回密码/修改密码 (二合一)
@admin_blue_1.route('/chg_psd', methods=['POST','GET'])
def chg_psd():
    fm=ChangePsd()
    if fm.validate_on_submit():
        in_name = fm.pre_username.data
        in_phone = fm.pre_phonenum.data
        in_email = fm.pre_email_ad.data
        in_code = fm.proofcode.data
        in_word=fm.new_password.data
        if in_code == session['email']:
            query_user = User.query.filter(User.username == in_name,User.phonenum == in_phone,User.email_ad == in_email).first()
            if query_user:
                query_user.set_password = in_word
                db.session.commit()
                flash('恭喜你，修改密码,自动前往登录界面')
                return redirect('/login')
            else:
                flash("存在错误，请重试！")
                return redirect('/chg_psd')
    else:
        return render_template("/admin/change_password.html",form=fm)

@admin_blue_1.route('/getinfo')
def send_info():
    get_data = request.args.to_dict()
    request_type = get_data.get("request_type")
    request_user = get_data.get("request_user")

    if request_type =="following":
        pass
    elif request_type =="fans":
        pass
    elif request_type =="article":
        user = User.query.get(current_user.id)
        temp={}
        i=0
        for a in user.articles:
            temp[i]=a.title
            i=i+1
        return jsonify(temp)
    elif request_type =="info":
        query_user = User.query.filter_by(username=request_user).first()

        temp={}

        temp["send_username"]=query_user.username

        temp["send_sex"]="男"

        temp["send_phonenum"]=query_user.phonenum

        temp["send_emial"]=query_user.email_ad

        temp["send_labels"]="<睡觉>   <摸鱼>    <上号>"

        return jsonify(temp)
    else:
        pass

@admin_blue_1.route('/upload',methods=['POST','GET'])# 获取用户名-----气死
def upload():#          文件格式没做筛选
    form = Upload_img()
    if request.method=="POST":

        # 获取用户名
        in_name = session["user"]#   实在实现不了post接收总是None，索性直接 全局session 保存一下得了

        # 获取类型为 <class 'werkzeug.datastructures.FileStorage'> 的文件
        user_img_Storage = request.files["user_img"]

        # 将上一步的文件 转化 为 bytes stream
        user_img_stream = user_img_Storage.stream.read()

        # 转化为 base64 编码字符
        image_base64 = str(base64.b64encode(user_img_stream), encoding='utf-8')  # image_base64即是对图像进行base64编码后的内容
        # 存入 数据库
        query_user = User.query.filter_by(username=in_name).first()

        query_user.user_img=image_base64

        return redirect('/userspace')
    return render_template('/admin/upload.html', form=form)

application/blog/__init__.py
from flask import Blueprint

blog_blue = Blueprint('blog',__name__)

from . import views,forms

application/blog/views.py
from flask_login import login_required,current_user
from . import blog_blue
from flask import render_template,redirect,session,flash
from .forms import CreatePost
from application import db
from application.models import Article


@blog_blue.route('/create_post',methods=["POST","GET"])
@login_required
def create_post():

    fm = CreatePost()
    if fm.validate_on_submit():

        in_title = fm.title.data
        in_body = fm.body.data
        in_categories = fm.categories.data

        new_article=Article(title=in_title,body=in_body,author_id=current_user.id,categories=in_categories)

        db.session.add(new_article)
        db.session.commit()
        flash("发布成功")
        return redirect("/")
    return render_template('/blog/write_post.html',form=fm)

application/main/__init__.py
from flask import Blueprint

main_blue = Blueprint('main',__name__)

from . import views,forms,errors

application/main/views.py
from flask_login import login_required

from . import main_blue

from flask import render_template

from application.models import Article

@main_blue.route('/')
@login_required# 如果你将这个装饰器放在视图上，它会保证你的当前用户是登录状态，并且在调用实际视图之前进行认证。
def index():#    如果当前用户不是系统认证的登录状态，它将调用LoginManager.unauthorized回调。
    articles=Article.query.order_by(Article.create_time.desc()).all()
    return render_template('index.html',articles=articles)


@main_blue.route('/test')
def test_case():
    return render_template('test.html')

application/templates/base.html
{%extends "bootstrap/base.html"%}



{#DIY_css+js#}
{%block head %}
{{ super() }}
    <style>
        * {
            margin: 0px;
            padding: 0px;
            background: linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%) no-repeat;
        }
        {#页脚css#}
        .foot-font{
        font-size: 40px;
        text-align: center;
        }

        {#flash消息css#}
        .hint{
            width: auto;
            background: red;
            color:white;
            margin-bottom: 20px;
        }

        {#login/register的css#}

        .login-box{
            margin-top: 80px;
            width: 100%;
            height: auto;
            text-align:center;
            margin-bottom: 100px;
        }
        .getin{
            margin-top: 10px;
            width: 200px;
            height: 30px;
        }
        .button{
            margin-top: 20px;
            width: 100px;
            height: 30px;

        }
    </style>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
    <script>
        setTimeout(function () {
            $("#hint_box").hide();
        }, 3000);
    </script>
{% endblock %}



{#界面标题#}
{%block title %}

{% endblock %}



{#界面导航条#}
{%block navbar %}
<nav class="navbar navbar-default">
{# 适应手机端 #}
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Forij的博客</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    {# nav主要内容 #}
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('main.index') }}">首页</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">分类<span class="caret"></span></a>
          <ul class="dropdown-menu" style="">
            <li><a target="_blank" href="#">学习笔记</a></li>
              <li role="separator" class="divider"></li>
            <li><a target="_blank" href="#">生活记事</a></li>
              <li role="separator" class="divider"></li>
            <li><a target="_blank" href="#">未知领域</a></li>
              <li role="separator" class="divider"></li>
            <li><a target="_blank" href="#">奇思妙想</a></li>
              <li role="separator" class="divider"></li>
            <li><a target="_blank" href="{{ url_for('main.test_case') }}">其他杂项</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="想知道什么?">
        </div>
          <button type="submit" class="btn btn-default">搜一搜</button>
      </form>
    <ul class="nav navbar-nav">

      </ul>
    {% if current_user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li><a target="_blank" href="{{ url_for('blog.create_post') }}">写文章</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ current_user.username }}的个人空间<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a target="_blank" href="{{url_for('admin_1.user_space',id=current_user.id)}}">空间</a></li>
            <li><a target="_blank" href="#">关注列表</a></li>
            <li><a target="_blank" href="#">动态</a></li>
            <li role="separator" class="divider"></li>{# 分界线 #}
            <li><a target="_blank" href="#">消息</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{ url_for('auth.logout') }}">退出登录</a></li>
          </ul>
        </li>
      </ul>
    {% else %}
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">登录/注册<span class="caret"></span></a>
          <ul class="dropdown-menu">
                <li> <a href="{{url_for('auth.login')}}">登录</a></li>
                <li><a href="{{url_for('auth.register')}}">注册</a></li>
          </ul>
        </li>
      </ul>
    {% endif %}

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}



{% block content %}

{% endblock %}

application/templates/index.html
{% extends 'base.html' %}

{% block title %}
博客主页
{% endblock %}

{% block content %}
    {#欢迎信息提示#}
    {% for message in get_flashed_messages() %}
    <div class="hint" id="hint_box">{{ message }}</div>
    {% endfor %}

<div class="container">
{% for a in articles %}
    <div class="panel panel-primary">
        <div class="panel-heading" style="padding-bottom: 0px;padding-top: 0px">
            <label data-toggle="collapse" data-target="#demo">
                <h3>{{ a.title }}</h3>
                <small >时间：{{ a.create_time }}</small>
                {# 根据文章找作者  a.user.username  #}
                <small ><a href="{{ url_for('admin_1.user_space',id=current_user.id) }}">作者：{{ a.user.username }}</a></small>
                <small >分类：{{ a.categories }}</small>
            </label>
        </div>

        <div id="demo"+loop.index class="collapse in">
            {{ a.body_html|safe|markdown }}
        </div>
    </div>
{% endfor %}

</div>


{% endblock %}

application/templates/test.html
{% extends 'base.html' %}

{% block title %}
测试bootstrap页面
{% endblock %}

{% block content %}

    <div class="container">
        这是带距离的容器 <span class="lead">你信吗</span>

    {#引用+描述(带有描述的短语列表。)#}
    <blockquote>
        <dl>
            <dt>个性签名</dt>
            <dd>没有，别看了</dd>
        </dl>
    </blockquote>


{#  水平描述(可用于展示个人信息)  #}
    <dl class="dl-horizontal">
      <dt>邮箱地址</dt>
      <dd>2292218440@qq.com</dd>
        <br>
      <dt>爱好</dt>
      <dd>睡觉</dd>
    </dl>
{#  代码块?  #}
<pre>
#include"iostream"
using namespace std;
int main()
{
    int n,a[10];
    cin>>n;

    return 0;
}
</pre>
    <div class="panel panel-default">
      <div class="panel-body">
        Basic panel example
      </div>
    </div>
    </div>


    <div class="container-fluid">
        这是100%的容器
    </div>
{% endblock %}